import '../assets/css/main.css'
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
import '../node_modules/bootstrap/dist/js/bootstrap.min.js'
import Hello from '../components/hello.jsx'
import './application.js'
